import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../components/Navbar";
import { Roboto } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: "teinda, onlñine"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
